### ISSUE TITLE
Bot not responding to new version app

### ISSUE THREAD

**Issue by hari6000** [lucioerlan/Whatsapp-Chatbot#4]
(node:24104) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded
    at new WaitTask (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:313:29)
    at Frame.waitForSelector (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51)
    at Page.waitForSelector (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2238:33)
    at Timeout.getQrCode [as _onTimeout] (C:\wamp64\www\bot\node_modules\whatsapp-web.js\src\Client.js:141:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24104) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded

**Comment by lucioerlan** [comment]
> (node:24104) UnhandledPromiseRejectionWarning: TimeoutError: aguardando o seletor `canvas`falhou: timeout 45000ms excedido na nova WaitTask (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ DOMWorld.js:509:34) em DOMWorld.waitForSelectorInPage (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:420:26) em Object.internalHandler.waitFor (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77) em DOMWorld.waitForSelector (C :\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:313:29) em Frame.waitForSelector (C:\wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51) em Page.waitForSelector (C:\ wamp64\www\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2238:33) em Timeout.getQrCode [as _onTimeout] (C:\wamp64\www\ bot\node_modules\whatsapp-web.js\src\Client.js:141:28) em runMicrotasks () em processTicksAndRejections (internal/process/task_queues.js:95:5) (Use `node --trace-warnings ...`para mostrar onde o aviso foi criado) (nó:24104) UnhandledPromiseRejectionWarning: Rejeição de promessa não tratada. Este erro se originou jogando dentro de uma função assíncrona sem um bloco catch ou rejeitando uma promessa que não foi tratada com .catch(). Para encerrar o processo do nó na rejeição de promessa não tratada, use o sinalizador da CLI `--unhandled-rejections=strict`(consulte https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (ID de rejeição: 1) (nó:24104) [DEP0018] DeprecationWarning: Rejeições de promessa não tratadas estão obsoletas. No futuro, as rejeições de promessas que não forem tratadas encerrarão o processo Node.js com um código de saída diferente de zero. (nó:24104) UnhandledPromiseRejectionWarning: TimeoutError: aguardando o seletor `canvas`falhou: tempo limite de 45000ms excedido

I recommend using node version 14 upwards
